GET http://localhost:8080/health


### 


POST http://localhost:8080
Content-Type: application/json

{
    "name": "Tamim",
    "country": "BD",
    "rank": 2
}


### 


GET http://localhost:8080

###

GET http://localhost:8080/w0-JOn8qw

### 

GET http://localhost:8080/tcLK1T7Xn


### 
PATCH http://localhost:8080/tcLK1T7Xn
Content-Type: application/json

{
    "name" : "Sakib Al Hasan"
}


### 
PUT http://localhost:8080/tamim-iqbal
Content-Type: application/json

{
    "name" : "Tamim Iqbal",
    "country": "Bangladesh",
    "rank": 20
}